version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved
    steps:
    - checkout
    - run: mkdir -p $TEST_RESULTS # create the test results directory
      # Download and cache dependencies
    - restore_cache:
      keys:
       - v1-dependencies-{{ checksum "pom.xml" }}
      # fallback to using the latest cache if no exact match is found
       - v1-dependencies-

       - run: mvn dependency:go-offline
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}
    - run: mvn test
